apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-db
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      pod-type: db
  replicas: 1
  template:
    metadata:
      labels:
        pod-type: db
    spec:
      containers:
      - name: container
        image: mysql:8.0.3
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: db-config

