apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: pod
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: container
        image: progress0407/docker-app
      terminationGracePeriodSeconds: 0