apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: pod
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: container
        image: progress0407/docker-app-ver2
      terminationGracePeriodSeconds: 0
