apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-was
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      pod-type: was
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        pod-type: was
    spec:
      containers:
      - name: container
        image: progress0407/docker-app-prod
        envFrom:
        - configMapRef:
            name: was-config
      terminationGracePeriodSeconds: 0
