apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    pod-type: db
spec:
  containers:
  - name: container
    image: mysql:8.0.3
    ports:
    - containerPort: 3306 # todo 필수값인지 재확인
    env:
    - name: MYSQL_DATABASE
      value: 'docker_app'
    # - name: MYSQL_ROOT_HOST
    #   value: '%'
    - name: MYSQL_ROOT_PASSWORD
      value: '1234'
    - name: TZ
      value: 'Asia/Seoul'
      