apiVersion: v1
kind: Pod
metadata:
  name: pod-was
  labels:
    pod-type: was
spec:
  containers:
  - name: container
    image: progress0407/docker-app-prod
    args:
    - "--server.port=8080"
    - "--spring.datasource.url=jdbc:mysql://db-forward:3306/docker_app?useSSL=false"