apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    type: web
    lo: dev
    app: pod
spec:
  containers:
  - name: container
    image: progress0407/docker-app
    args:
    - "--server.port=8080"
