### direct request first-service
GET http://localhost:8081/first-service/welcome

### direct request second-service
GET http://localhost:8082/second-service/welcome

### first-service request by gateway
GET http://localhost:8000/first-service/check

### second-service request by gateway
GET http://localhost:8000/second-service/welcome

### second-service request by gateway
GET http://localhost:8000/second-service/welcome

### user-service get request by gateway
GET http://localhost:8000/user-service/welcome

### user-service post request by gateway
POST http://localhost:8000/user-service
Content-Type: application/json

{
  "email": "hello@google.com",
  "name": "sw cho",
  "password": "1234"
}
