### direct request first-service
GET http://localhost:8081/first-service/welcome

### direct request second-service
GET http://localhost:8082/second-service/welcome

### first-service request
GET http://localhost:8000/first-service/check

### second-service request
GET http://localhost:8000/second-service/welcome

### second-service request
GET http://localhost:8000/second-service/welcome

### user-service get request
GET http://localhost:8000/user-service/welcome

### user-service post request
POST http://localhost:8000/user-service
Content-Type: application/json

{
  "email": "hello@google.com",
  "name": "sw cho",
  "password": "1234"
}

### user-service find All
GET http://localhost:8000/user-service/users

### user-service find by id
GET http://localhost:8000/user-service/users/1
