### Health Check
GET http://localhost:8000/order-service/health_check

### Order "CATALOG-001"
POST http://localhost:8000/order-service/b1c4ff32-9d33-4bb9-b52f-842d59d40c80/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "orderQuantity": 10,
  "unitPrice": 1500
}

### Order "CATALOG-002"
POST http://localhost:8000/order-service/b1c4ff32-9d33-4bb9-b52f-842d59d40c80/orders
Content-Type: application/json

{
  "productId": "CATALOG-002",
  "orderQuantity": 5,
  "unitPrice": 1000
}

### List
GET http://localhost:8000/order-service/607d95b8-037b-4174-89db-2804cbed9fe8/orders
