### Health Check
GET http://localhost:8000/order-service/health_check

### Order "CATALOG-001"
POST http://localhost:8000/order-service/fc0b7425-3918-45f1-b746-3ba614c72a97/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "orderQuantity": 10,
  "unitPrice": 1500
}

### Order "CATALOG-002"
POST http://localhost:8000/order-service/fc0b7425-3918-45f1-b746-3ba614c72a97/orders
Content-Type: application/json

{
  "productId": "CATALOG-002",
  "orderQuantity": 5,
  "unitPrice": 1000
}

### List
GET http://localhost:8000/order-service/607d95b8-037b-4174-89db-2804cbed9fe8/orders


### Order For User
GET http://localhost:8000/order-service/4a8fc24a-54a3-43c6-b0ef-b2222b2fb50f/orders
