### Health Check
GET http://localhost:8000/user-service/health_check


### Welcome
GET http://localhost:8000/user-service/welcome


### Sign Up
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "hello@google.com",
  "name": "sw cho",
  "password": "1234"
}


### Login
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "hello@google.com",
  "password": "1234"
}


### List
GET http://localhost:8000/user-service/users


### Detail
GET http://localhost:8000/user-service/users/1
