### App Info
GET http://localhost:8000/user-service/users/app-info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1MzM3OTI5LCJleHAiOjE2ODU0MjQzMjl9.pFbdw2b-wJwcsFZjjKYZWU9HmsVQVG6ZAj-CQxBpTT2o4en8ETzRjYFWAQTigcLCrbLLtSh4HpmWC2pn3ohAqg

### Direct App Info
GET http://localhost:2980/users/app-info

### Direct Refresh
POST http://localhost:2980/actuator/refresh

### Direct Bus Refresh
POST http://localhost:2980/actuator/busrefresh

// a38d552e-8572-4fd3-a6dd-8408fefa551c

### Direct Sign Up
POST http://localhost:3499/users
Content-Type: application/json

{
  "email": "hello@google.com",
  "name": "sw cho",
  "password": "1234"
}

### Direct Login
POST http://localhost:3499/login
Content-Type: application/json

{
  "email": "hello@google.com",
  "password": "1234"
}

### Direct List
GET http://localhost:3499/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4YjlkYmQ1MC03MWQ5LTQzYzEtYjgwOS01ZTUwNDcwOWNkNDciLCJpYXQiOjE2ODU3MDg3OTksImV4cCI6MTY4NTc5NTE5OX0.ycBvxxkxTDEam07eK_sblpSPx9jcRCSnt6aN1p9_yMZqGCJyZKxrjJEKDvalDUig-7b5k_gXVpE0ckd7eLbihg

### Direct Detail
GET http://localhost:3499/users/8b9dbd50-71d9-43c1-b809-5e504709cd47
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4YjlkYmQ1MC03MWQ5LTQzYzEtYjgwOS01ZTUwNDcwOWNkNDciLCJpYXQiOjE2ODU3MDg3OTksImV4cCI6MTY4NTc5NTE5OX0.ycBvxxkxTDEam07eK_sblpSPx9jcRCSnt6aN1p9_yMZqGCJyZKxrjJEKDvalDUig-7b5k_gXVpE0ckd7eLbihg


### Health Check
GET http://localhost:3290/user-service/health-check
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1MjY0MDY4LCJleHAiOjE2ODUzNTA0Njd9.NIKJl7mBmFdnMcEGZeMBM_3HIKCJBgDx165VO-gEURX2ZthgF4W7aPNxGYanccN14_zSlwzJRz4QGgn7yM5aGA

### Welcome
GET http://localhost:8000/user-service/welcome
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg0OTAzMDIyLCJleHAiOjE2ODQ5ODk0MjJ9.JuM3ASUpGfOukRaa89Ha1O7-p5i3Gb1h1JpQwPMllIZlDtVcnT6B3DqMWJcYzkdFelEKh7HOY-IwJ3eL3VvTsA

### Sign Up
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "hello@google.com",
  "name": "sw cho",
  "password": "1234"
}

### Login
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "hello@google.com",
  "password": "1234"
}

### List
GET http://localhost:8000/user-service/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1NjQzNTE2LCJleHAiOjE2ODU3Mjk5MTZ9.Ufqw-PzSQKMzDdTPeHDcj9Vz83W_s92TfjMQEIeCDqtNQ8SOyzHnJqVWzlGzcYV6yTYZ_2OSIk8M4zqnxO7IZw

### Detail
GET http://localhost:8000/user-service/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1NjQzNTE2LCJleHAiOjE2ODU3Mjk5MTZ9.Ufqw-PzSQKMzDdTPeHDcj9Vz83W_s92TfjMQEIeCDqtNQ8SOyzHnJqVWzlGzcYV6yTYZ_2OSIk8M4zqnxO7IZw

### Refresh
GET http://localhost:8000/user-service/actuator/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1MjUwOTEwLCJleHAiOjE2ODUzMzczMTB9.RroSOzt5TsqKuCGihEIccPoIJ_xsK2_MzB5cSJ55sUvHfHrWbz5XZlRbF3dkBOLKAiTfB4TK37IJDIOKBdHghw
