spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect # mysql
    hibernate:
#      use-new-id-generator-mappings: false # mysql
      ddl-auto: create # ddl-auto

logging.level:
  org.hibernate:
    SQL: debug
    type: trace
