server:
  port: 8888

spring:
  application.name: config-service
  cloud.config.server:
#    git.uri: 'file://${user.dir}/../../../../leedowon-msa-spring-cloud-configuration'
    git.uri: 'file:///C:/dev/5.%20projects/3.%20global/leedowon-msa-spring-cloud-configuration'
