server:
  port: 8888

spring:
  application.name: config-service
  cloud.config.server:
    native:
      search-locations: 'file:///C:/dev/5.%20projects/3.%20global/leedowon-msa-spring-cloud-configuration'
  profiles:
    active: native

management.endpoints.web.exposure.include: refresh, health, beans, busrefresh
