spring:
  datasource:
    url: jdbc:h2:~/test # ?? ? ?
#    url: jdbc:h2:tcp://localhost/~/jpashop # ?? ??
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  config: classpath:log4j2.xml
  level:
    org.hibernate:
      SQL: debug
  #      type: trace
