spring:
  datasource:
#    url: jdbc:h2:~/querydsl
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      show_sql: true # sysout 기존
      format_sql: true
      use_sql_comments: true # querydsl -> jpql 로 변환되는 것을 보여줌

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
