server:
  port: 0

spring:
  application:
    name: philz-first-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
